apiVersion: apps/v1
kind: Deployment
metadata:
  name: swe-645-a2-cluster
  labels:
    app: studentsurvey
spec:
  replicas: 3
  selector:
    matchLabels:
      app: studentsurvey
  template:
    metadata:
      labels:
        app: studentsurvey
    spec:
      containers:
      - name: container-0
        image: saik11/studentsurvey645:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always